--- #YAML:1.0
name:                POE-Component-SSLify-NonBlock
version:             0.40
abstract:            Nonblocking SSL for POE with client certificate verification.
license:             ~
author:              
    - Markus Mueller <pRiVi@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Net::SSLeay:                   1.32
    POE::Component::SSLify:        0.06
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
